# This is a basic workflow to help you get started with Actions

name: CRAWLER

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-crawler]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      DOCUSAURUS_REPOSITORY: ${{ secrets.DOCUSAURUS_REPOSITORY }}
      PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout backend repo 
        uses: actions/checkout@v2
        with:
          path: backend-repo

      - name: Checkout docusaurus repo
        uses: actions/checkout@v2
        with:
          # repository: redis-developer/redis-developer.github.io
          # temporary fork
          repository: RisingStack/redis-developer.github.io 
          path: ${{ env.DOCUSAURUS_REPOSITORY }}
          token: ${{ env.PERSONAL_ACCESS_TOKEN_GITHUB }}
          # for testing
          # ref: feat/marketplace-docs

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare repos
        run: |
          # remove old documentation
          rm -rfv $DOCUSAURUS_REPOSITORY/docs/marketplace
          # empty sidebar config
          echo "[]" > $DOCUSAURUS_REPOSITORY/marketplace-sidebar.json

      - name: Run script
        env:
          PORT: ${{ secrets.PORT }}
          REDIS_CONNECTION_STRING: ${{ secrets.REDIS_CONNECTION_STRING }}
        run: |
          cd ./backend-repo
          npm ci
          npm run crawler

      - name: Commit changes
        run: |
          cd $DOCUSAURUS_REPOSITORY
          # configure git and commit changes
          git config --global user.email "info@risingstack.com"
          git config --global user.name "RisingBot"
          git diff
          git add -A
          git commit -m 'RisingBot: Generate Marketplace readme' || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: ${{ env.DOCUSAURUS_REPOSITORY }}
          github_token: ${{ env.PERSONAL_ACCESS_TOKEN_GITHUB }}
          repository: RisingStack/redis-developer.github.io
          branch: master
